### ISSUE TITLE
Alt+Tab Window Switch in XFCE4

### ISSUE THREAD

**Issue by bunnymnemonic** [sleekmason/extra-themes#1]
Hi, thank you very much for your themes, they are beautiful!
I am also happy to see that there is a new XFCE4 version.
There is one small issue: when using a light theme (Broadwater, Ghost) in XFCE4, the window switcher (Alt + Tab) shows dark text on dark background.

**Comment by sleekmason** [comment]
Thank you so much for bringing this to my attention!

There will be new releases tomorrow for all of the builds both openbox and
xfce.  The alt tab combo will now follow the system theme correctly for all
of the themes in the new release.

Really neat that I was able to get this email today and take care of this!

Please let me know if you find anything else bothersome, or some sort of
bug that needs to be fixed.

And of course, join the forum if you get a chance. :)

Thanks again and best regards, David

**Comment by bunnymnemonic** [comment]
Wow, that was really quick, thank you! Also, thank you for the invitation. I've just discovered Lilidog, testing it in VM and I like it very much!
